'use strict';
let csrf='', user=null, mode='demo', page='overview', overview=null, logBefore=0, logQuery='';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=t=>t?new Date(t*1000).toLocaleString():'Not received';
const num=(n,d=1)=>n===null||n===undefined?'—':Number(n).toFixed(d);
const badge=s=>`<span class="pill ${esc(s)}">${esc(String(s).replaceAll('_',' '))}</span>`;
const canEdit=()=>user&&user.role!=='viewer';
const titles={overview:['Network overview','Network health and security activity, together.'],alerts:['Security alerts','Review detection signals and acknowledge investigated alerts.'],incidents:['Incident workspace','Investigate, contain, recover and record what you learned.'],devices:['Device inventory','DHCP devices observed by the router. Static-IP devices may be absent.'],logs:['Live logs','Latest received syslog messages. All messages are generated examples.'],rules:['Detection rules','Thresholds are starting points. Tune them to your network.'],reports:['Export reports','CSV exports include up to the latest 10,000 records.'],users:['User management','Control access to this local organization.'],audit:['Audit trail','Recent account, configuration and incident actions.']};
async function api(url,method='GET',data){return Demo.request(url,method,data);}
function fail(e){$('#error').textContent=e.message;$('#error').hidden=false;}
function table(head,body){return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${body.length?body.join(''):`<tr><td colspan="${head.length}" class="empty">No records yet.<br>Try a simulated action to add a record.</td></tr>`}</tbody></table></div>`;}
function panel(title,sub,body){return `<section class="panel"><div class="panel-heading"><div><h2>${esc(title)}</h2><p>${esc(sub)}</p></div></div>${body}</section>`;}
function stat(label,value,foot){return `<div class="stat"><div class="stat-label">${esc(label)}<span>↗</span></div><div class="stat-value">${value}</div><div class="stat-foot">${esc(foot)}</div></div>`;}
function chart(history){if(!history.some(x=>x.tx_mbps!==null))return '<div class="empty">Waiting for two successful router polls to calculate bandwidth.</div>';const max=Math.max(1,...history.flatMap(x=>[x.tx_mbps||0,x.rx_mbps||0]));let lines='';for(let i=0;i<4;i++){const y=15+i*45;lines+=`<line class="grid" x1="42" y1="${y}" x2="600" y2="${y}"/><text x="0" y="${y+4}">${(max*(3-i)/3).toFixed(1)}</text>`;}for(const [field,cls]of[['rx_mbps','rx'],['tx_mbps','tx']]){let segment=[];const flush=()=>{if(segment.length)lines+=`<polyline class="${cls}" points="${segment.join(' ')}"/>`;segment=[];};history.forEach((p,i)=>{if(p[field]===null){flush();return;}segment.push(`${42+i*558/Math.max(history.length-1,1)},${150-p[field]/max*135}`);});flush();}return `<svg class="chart" viewBox="0 0 610 175" role="img" aria-label="Recent WAN upload and download in megabits per second">${lines}<text x="42" y="173">${esc(new Date(history[0].collected_at*1000).toLocaleTimeString())}</text><text x="520" y="173">Latest</text></svg><div class="legend"><span class="upload">● Upload Mbps</span><span>● Download Mbps</span><span>Average between polls</span></div>`;}
function alertRows(items){return items.map(a=>`<tr><td>${badge(a.severity)}</td><td><strong>${esc(a.title)}</strong><br><small>#${a.id} · ${esc(a.rule_key)}</small></td><td>${esc(a.source)}</td><td>${date(a.created_at)}</td><td>${badge(a.status)}</td><td>${canEdit()&&a.status==='open'?`<button class="table-button" data-ack="${a.id}">Acknowledge</button>`:''}</td></tr>`);}
async function render(){if(!user)return;$('#error').hidden=true;$('#page-title').textContent=titles[page][0];$('#page-subtitle').textContent=titles[page][1];$('#breadcrumb').textContent=titles[page][0];document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));let html='';if(page==='overview'){const [o,a]=await Promise.all([api('/api/overview'),api('/api/alerts')]);overview=o;const m=o.metric||{},r=o.router;html=`<div class="stats">${stat('Router status',badge(mode==='demo'?'demo':r.status),r.name+' · '+r.ip)}${stat('CPU utilization',num(m.cpu,0)+'<span class="metric-unit">%</span>','Memory '+num(m.memory_percent,0)+'%')}${stat('Open alerts',o.counts.open_alerts,'Unacknowledged security signals')}${stat('Active incidents',o.counts.active_incidents,o.counts.devices+' devices in inventory')}</div><div class="grid-two">${panel('WAN traffic','Interface '+esc(mode==='demo'?'ether1 (synthetic)':'configured WAN')+' · up to 60 samples',chart(o.history))}${panel('Router health','Collection status and most recent telemetry',`<div class="key-values"><div><span>Uptime</span><strong>${esc(m.uptime||'—')}</strong></div><div><span>Syslog listener</span><strong>${esc(o.collector.syslog||'Unknown')}</strong></div><div><span>Last API sample</span><strong>${date(r.last_poll)}</strong></div><div><span>Last received log</span><strong>${date(r.last_syslog)}</strong></div><div><span>Accepted / dropped logs</span><strong>${o.collector.accepted||0} / ${o.collector.dropped||0}</strong></div><div><span>Router response</span><strong>${'Simulated only'}</strong></div></div><p class="rule-note">${esc(r.error||'A quiet log stream does not prove the router is offline. API status reflects the last successful poll.')}</p>`)}</div>${panel('Recent security alerts','Signals require investigation; they are not confirmed attacks.',table(['Severity','Detection','Source','Received','Status',''],alertRows(a.items.slice(0,6))))}${panel('Interfaces','Synthetic interface snapshot',table(['Name','Link','Administrative state'],(m.interfaces?JSON.parse(m.interfaces):[]).map(i=>`<tr><td>${esc(i.name)}</td><td>${i.running==='true'?'Up':'Down'}</td><td>${i.disabled==='true'?'Disabled':'Enabled'}</td></tr>`)))}`;}
else if(page==='alerts'){const a=await api('/api/alerts');html=panel('Alerts','Latest 200 · detection evidence is available in the corresponding incident.',table(['Severity','Detection','Source','Received','Status',''],alertRows(a.items)));}
else if(page==='incidents'){const a=await api('/api/incidents');window.incidents=a.items;html=panel('Investigation queue','Latest 200 incidents · one per alert',table(['Incident','Severity','Source','Stage','Assignee',''],a.items.map(i=>`<tr><td><strong>#${i.id} ${esc(i.title)}</strong><br><small>Updated ${date(i.updated_at)}</small></td><td>${badge(i.severity)}</td><td>${esc(i.source)}</td><td>${badge(i.stage)}</td><td>${esc(i.assignee||'Unassigned')}</td><td><button class="table-button" data-incident="${i.id}">Open incident</button></td></tr>`)));const responses=await api('/api/response_actions');html+=panel('Router response history','All responses here are simulations; no router command is sent.',table(['Time','Incident','Action','Target','Outcome'],responses.items.map(r=>`<tr><td>${date(r.created_at)}</td><td>#${r.incident_id}</td><td>${esc(r.action)}</td><td>${esc(r.target)}</td><td>${badge(r.status)}<br><small>${esc(r.detail)}</small></td></tr>`)));}
else if(page==='devices'){const a=await api('/api/devices');html=panel('Observed devices','The first successful DHCP snapshot establishes a baseline without alerts. Latest 200 devices.',table(['Device','IPv4 address','MAC address','Last observed','Trust',''],a.items.map(d=>`<tr><td><strong>${esc(d.hostname||'Unnamed device')}</strong></td><td>${esc(d.ip)}</td><td><code>${esc(d.mac)}</code></td><td>${date(d.last_seen)}</td><td>${d.trusted?'Trusted':'Unreviewed'}</td><td>${canEdit()?`<button class="table-button" data-trust="${d.id}" data-value="${!d.trusted}">${d.trusted?'Remove trust':'Mark trusted'}</button>`:''}</td></tr>`)));}
else if(page==='logs'){const a=await api('/api/logs?q='+encodeURIComponent(logQuery)+'&before='+logBefore);html=`<form id="log-search" class="toolbar"><input name="q" placeholder="Search log messages…" aria-label="Search logs" value="${esc(logQuery)}"><button>Search</button><button type="button" class="secondary" id="latest-logs">Latest</button></form>`+panel('Syslog stream','100 records per page · IPv4 parsing · receipt timestamps',table(['Received','Type','Source','Message'],a.items.map(l=>`<tr><td>${date(l.received_at)}</td><td>${badge(l.kind)}</td><td>${esc(l.src_ip||'—')}</td><td class="message">${esc(l.message)}</td></tr>`)))+(a.next_before?`<button class="secondary" id="older-logs" data-before="${a.next_before}">Load older logs</button>`:'');}
else if(page==='rules'){const a=await api('/api/rules');window.rules=a.items;html=panel('Detection configuration','Upload threshold uses Mbps; scan uses distinct ports; SSH enumeration uses distinct usernames.',table(['Detection','Threshold','Window','Cooldown','Severity','State',''],a.items.map(r=>`<tr><td><strong>${esc(r.title)}</strong></td><td>${r.threshold}${r.key==='exfiltration'?' Mbps':''}</td><td>${r.window_seconds}s</td><td>${r.cooldown_seconds}s</td><td>${badge(r.severity)}</td><td>${r.enabled?'Enabled':'Disabled'}</td><td>${user.role==='admin'?`<button class="table-button" data-rule="${r.key}">Edit</button>`:''}</td></tr>`)))+panel('Coverage notes','Know what the sensors can actually observe.','<p>Port scans count distinct destination ports per source in received firewall logs. SSH enumeration uses distinct usernames in failed SSH logins, not packet fingerprinting. Device alerts use DHCP lease discovery. Upload anomalies use aggregate WAN transmit counters; legitimate backups can trigger them. Rate-limited logs and FastTrack can reduce visibility. This edition does not inspect payloads or encrypted traffic.</p>');}
else if(page==='reports'){html='<div class="report-grid">'+['alerts','incidents','logs','devices','metrics'].map(k=>`<section class="panel"><h2>${k[0].toUpperCase()+k.slice(1)}</h2><p>Export recorded ${k} for analysis or documentation.</p><a href="#" data-export="${k}">Download CSV ↓</a></section>`).join('')+'</div><p>Times in CSV are Unix seconds (UTC). CSV cells that could be interpreted as spreadsheet formulas are escaped. Exports contain network identifiers; store them appropriately.</p>';}
else if(page==='users'){const a=await api('/api/users');window.users=a.items;html='<div class="toolbar"><button id="new-user">Add user</button></div>'+panel('Workspace accounts','Admin: all actions · Analyst: investigation and trust · Viewer: read and export',table(['Username','Role','Status',''],a.items.map(u=>`<tr><td>${esc(u.username)}</td><td>${badge(u.role)}</td><td>${u.active?'Active':'Disabled'}</td><td>${u.id!==user.id?`<button class="table-button" data-user="${u.id}">Edit access</button>`:'Current account'}</td></tr>`)));}
else if(page==='audit'){const a=await api('/api/audit');html=panel('Recent audit events','Latest 200 · retained independently of raw logs',table(['Time','Actor','Action','Details'],a.items.map(a=>`<tr><td>${date(a.at)}</td><td>${esc(a.actor)}</td><td>${esc(a.action)}</td><td class="message">${esc(a.detail)}</td></tr>`)));}
$('#content').innerHTML=html;$('#updated').textContent='Updated '+new Date().toLocaleTimeString();bindContent();}
function modal(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html+'<p class="modal-error" role="alert"></p>';$('#modal').showModal();}
function appendIntelligence(id){const incident=window.incidents.find(x=>x.id===id);if(!incident||!/^\d+\.\d+\.\d+\.\d+$/.test(incident.source))return;const container=document.createElement('div');container.className='actions';const button=document.createElement('button');button.className='secondary';button.textContent='Look up offline IP intelligence';const result=document.createElement('pre');result.hidden=true;button.onclick=async()=>{try{result.textContent=JSON.stringify(await api('/api/intelligence/'+encodeURIComponent(incident.source)),null,2);result.hidden=false;}catch(e){$('.modal-error').textContent=e.message;}};container.append(button);$('#modal-body').append(container,result);}
function formSave(fn){$('#modal-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await fn(Object.fromEntries(new FormData(e.target)));$('#modal').close();await render();}catch(err){$('.modal-error').textContent=err.message;}finally{b.disabled=false;}});}
function options(values,selected){return values.map(v=>`<option value="${v}" ${v===selected?'selected':''}>${v.replaceAll('_',' ')}</option>`).join('');}
function bindContent(){document.querySelectorAll('[data-ack]').forEach(b=>b.onclick=()=>api(`/api/alerts/${b.dataset.ack}/ack`,'POST',{}).then(render).catch(fail));document.querySelectorAll('[data-trust]').forEach(b=>b.onclick=()=>api(`/api/devices/${b.dataset.trust}/trust`,'POST',{trusted:b.dataset.value==='true'}).then(render).catch(fail));document.querySelectorAll('[data-incident]').forEach(b=>b.onclick=()=>{openIncident(Number(b.dataset.incident));appendIntelligence(Number(b.dataset.incident));});document.querySelectorAll('[data-rule]').forEach(b=>b.onclick=()=>editRule(b.dataset.rule));document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>editUser(Number(b.dataset.user)));if($('#new-user'))$('#new-user').onclick=newUser;if($('#log-search'))$('#log-search').onsubmit=e=>{e.preventDefault();logQuery=new FormData(e.target).get('q');logBefore=0;render().catch(fail);};if($('#latest-logs'))$('#latest-logs').onclick=()=>{logBefore=0;render().catch(fail);};if($('#older-logs'))$('#older-logs').onclick=e=>{logBefore=Number(e.target.dataset.before);render().catch(fail);};}
function openIncident(id){const i=window.incidents.find(x=>x.id===id);const editable=canEdit();modal(`Incident #${id} · ${i.title}`,`<p>${badge(i.severity)} Source: <strong>${esc(i.source)}</strong></p><h3>Detection evidence</h3><pre>${esc(JSON.stringify(JSON.parse(i.evidence),null,2))}</pre><form id="modal-form"><div class="form-row"><label>Stage<select name="stage" ${editable?'':'disabled'}>${options(['detected','investigation','containment','recovery','lessons_learned','closed'],i.stage)}</select></label><label>Assignee<input name="assignee" maxlength="64" value="${esc(i.assignee)}" ${editable?'':'disabled'}></label></div><label>Investigation, recovery and lessons learned<textarea name="notes" maxlength="8000" ${editable?'':'disabled'}>${esc(i.notes)}</textarea></label>${editable?'<button>Save incident</button>':''}</form>${editable&&['port_scan','brute_force','ssh_enumeration'].includes(i.rule_key)?'<div class="actions"><button id="preview-response" class="secondary">Preview simulated containment</button></div><div id="response-preview"></div>':''}`);if(editable)formSave(d=>api('/api/incidents/'+id,'POST',d));if($('#preview-response'))$('#preview-response').onclick=async()=>{try{const p=await api(`/api/incidents/${id}/response`);$('#response-preview').innerHTML=`<pre>${esc(p.command)}</pre><p>${esc(p.note)}</p><p>Unblock removes only this incident’s entries. Other entries for this source may remain.</p>${user.role==='admin'?`<label>Type CONFIRM ${id}<input id="response-confirm" autocomplete="off"></label><div class="actions"><button id="block" class="danger">Simulate one-hour block</button><button id="unblock" class="secondary">Simulate unblock</button></div>`:''}`;for(const a of ['block','unblock'])if($('#'+a))$('#'+a).onclick=async()=>{const b=$('#'+a);b.disabled=true;try{const r=await api(`/api/incidents/${id}/response`,'POST',{action:a,confirmation:$('#response-confirm').value});$('.modal-error').textContent=r.status+': '+r.detail;}catch(e){$('.modal-error').textContent=e.message;}finally{b.disabled=false;}};}catch(e){$('.modal-error').textContent=e.message;}};}
function editRule(key){const r=window.rules.find(x=>x.key===key);modal('Edit '+r.title,`<form id="modal-form"><label>Threshold ${key==='exfiltration'?'(Mbps)':''}<input type="number" name="threshold" step="any" min="0.01" max="100000" value="${r.threshold}" required ${key==='new_device'?'readonly':''}></label><div class="form-row"><label>Window (seconds)<input type="number" name="window_seconds" value="${r.window_seconds}" min="30" max="86400" required></label><label>Cooldown (seconds)<input type="number" name="cooldown_seconds" value="${r.cooldown_seconds}" min="30" max="604800" required></label></div><label>Severity<select name="severity">${options(['low','medium','high','critical'],r.severity)}</select></label><label><input name="enabled" type="checkbox" ${r.enabled?'checked':''}> Enabled</label><div class="actions"><button>Save rule</button></div></form>`);formSave(d=>api('/api/rules/'+key,'POST',{...d,enabled:d.enabled==='on'}));}


async function boot(){const s=await api('/api/session');csrf=s.csrf;user=s.user;mode=s.mode;$('#login').hidden=!!user;$('#shell').hidden=!user;if(user){$('#username').textContent=user.username+' · '+user.role;$('#organization').textContent=s.organization;$('#mode').textContent=mode==='demo'?'Demo · synthetic data':'Live monitoring';$('#mode').className='pill '+mode;document.querySelectorAll('.admin-only').forEach(e=>e.hidden=user.role!=='admin');$('#notice').hidden=mode!=='demo';$('#notice').textContent='DEMO WORKSPACE — All sample telemetry and alerts are synthetic. No router is contacted. Try acknowledging an alert, editing an incident, or exporting a report. Changes stay in this browser; Reset demo restores the samples.';page='overview';await render();}}


$('#refresh').onclick=()=>render().catch(fail);
$('#close-modal').onclick=()=>$('#modal').close();
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render().catch(fail);});
$('#account').onclick=()=>{modal('Reset this browser demo','<p>Restore the sample alerts, incidents and rules? This affects only demo changes in this browser.</p><button id="confirm-reset">Reset sample data</button>');$('#confirm-reset').onclick=()=>{Demo.reset();$('#modal').close();page='overview';render().catch(fail);};};
setInterval(()=>{if(user&&!$('#modal').open&&['overview','alerts','logs'].includes(page)&&!logBefore&&document.activeElement?.tagName!=='INPUT')render().catch(fail);},15000);
boot().catch(fail);

document.addEventListener('click',e=>{const link=e.target.closest('[data-export]');if(link){e.preventDefault();Demo.download(link.dataset.export);}});
